<hr size="15" align="left" width="100%" color="#FF0000">
<a class="btn btn-primary" href="<?php echo $this->url('morador', array('controller' => 'morador', 'action' => 'add')); ?>">Cadastrar</a>
<hr size="15" align="left" width="100%" color="#FF0000">
<?php
if ($this->success)
    echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

if ($this->error)
    echo '<div class="alert alert-danger">'.$this->error[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';
?>
<table class="table table-bordered table-striped table-hover table-condensed">
    <?php if (count($this->data) > 0): ?>
    	<thead>
    	<tr>
        <th width="4%">ID</th>
		<th width="25%">NOME</th>
        <th width="10%">UNIDADE</th>
        <th width="10%">CPF</th>
        <th width="5%">DOCUMENTO</th>
        <th width="8%">CELULAR</th>
        <th width="8%">NASCTO</th>        
        <th width="7%">AÇÃO</th>
    	</tr>
    	</thead>
    	<tbody>
    	<?php
    	/**
    	* @var $entity \Categoria\Entity\Morador
  	   	*/
		?>
        <?php foreach( $this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
			<td><?php echo $entity->getNome(); ?></td>            
            <td><?php echo $entity->getUnidade()->getDescricao(); ?></td>
			<td><?php echo $entity->getCpf(); ?></td>            
            <td><?php echo $entity->getDocumento(); ?></td>
            <td><?php echo $entity->getCelular(); ?></td>             
			<td><?php echo (null !==$entity->getDatanascto()) ? $entity->getDatanascto() : '' ; ?></td>
            <td>
                <a class="btn btn-success" href="<?php echo $this->url('morador', array('controller' => 'morador', 'action' => 'edit'  , 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-pencil"></i> </a>
                <a class="btn btn-danger"  href="<?php echo $this->url('morador', array('controller' => 'morador', 'action' => 'delete', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-remove-sign"></i> </a>
            </td>
        </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <p>Nenhum registro encontrado!</p>
    <?php endif; ?>
    </tbody>
</table>

<?php echo $this->paginationControl(  $this->data,    'sliding',    'partial/paginator.phtml',    array('route' => 'morador')); ?>