<?php
namespace Portaria\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends EntityRepository
{
	public function findAll()
	{
		
		$dql = "SELECT m FROM Portaria\Entity\modelo m JOIN m.marca t ORDER BY t.descricao,m.descricao";
		$query = $this->getEntityManager()->createQuery($dql);
		return $query->getResult();
	}
}