<?php
namespace Portaria\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * UnidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadeRepository extends EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('descricao' => 'ASC'));
	}
}