<hr size="15" align="left" width="100%" color="#FF0000">
<h3>Alterar</h3>
<hr size="15" align="left" width="100%" color="#FF0000">
<?php
    /**
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;

    if ($this->success)
        echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

    if ($this->error)
        echo '<div class="alert alert-warning">'.$this->error[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

    $this->formElementErrors()
        ->setMessageOpenFormat ('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
        ->setMessageCloseString ('</div>')
        ->render ($form);

    $form->setAttribute('action', $this->url('unidadetipo', array('controller' => 'unidadetipo', 'action' => 'edit', 'id' => $this->id)));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('descricao'));
echo '<hr size="15" align="left" width="100%" color="#FF0000">';
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
?>